#################
## Controllers ##
#################
rail:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    position:
      rail_joint:
        type: velocity_controllers/JointPositionController
        joint: rail_joint
    rail_controller:
      type: velocity_controllers/JointTrajectoryController
      action_monitor_rate: 50
      joints:
        - rail_joint
      constraints:
        goal_time: 1.0
        rail_joint: { goal: 0.01, trajectory: 0.02 }
        stopped_velocity_tolerance: 0.05
      gains:
        rail_joint: { p: 25.0, i: 0.0, d: 0.0, i_clamp: 0.0 }
      stop_trajectory_duration: 1.0
