#################
## Controllers ##
#################
EWDL:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    position:
      rail_joint:
        type: position_controllers/JointPositionController
        joint: "rail_joint"
        pid: { p: 10.0, i: 0.0, d: 1.0 }
