#####################
## EtherCAT Master ##
#####################

ifname: enp7s0f1
  # EtherCAT Master interface
slaves:
  - device_name: "EWDL Servo"
    # Homing
    homing_method: 1                    #
    homing_speed: [ 50000, 20000 ]      # Homing Speed to switch and to return to zero.
    homing_acceleration: 1000000        #
    home_offset: 1750                   #
    home_switch: 0x08                   #
    # In Position
    in_position_counts: 0               # Position counts to determine if the motor is in position (dynamic).
    in_position_error_range: 20         # Position counts to determine if the motor is in position (static).
    in position_timing: 20              # Time duration for in-position judging condition. [x 200us]
    # QuickStop
    quickstop_deceleration: 3000000
