#####################
## EtherCAT Master ##
#####################

ifname: enp7s0f1
  # EtherCAT Master interface
slaves:
  - device_name: "EWDL Servo"
    # Homing
    homing_method: 1                    #
    homing_speed: [ 50000, 20000 ]      # Homing Speed to switch and to return to zero.
    homing_acceleration: 1000000        #
    home_offset: 0                      #
    home_switch: 0x08                   #
    # Following Error Window
    following_error_window: 10000       # Range of tolerated position values respect to the commanded position value.
    # In Position
    in_position_counts: 20              # Position counts to determine if the motor is in position (dynamic).
    in_position_error_range: 10         # Position counts to determine if the motor is in position (static).
    in_position_timing: 10              # Time duration for in-position judging condition. [x 200us]
    # QuickStop
    quickstop_deceleration: 3000000
