#####################
## EtherCAT Master ##
#####################

ifname: enp7s0f1
  # EtherCAT Master interface
slaves:
  - device_name: "EWDL Servo"
    # Homing
    homing_method: 2                    #
    homing_speed: [ 10000, 2000 ]       # Homing Speed to switch and to return to zero.
    homing_acceleration: 10000          #
    home_offset: -6950                  #
    home_switch: 0x08                   #
    # QuickStop
    quickstop_deceleration: 3000000
